### ISSUE TITLE
Lightmap UV are overlapping

### ISSUE THREAD

**Issue by iwatakeshi** [pokefarm/soccerfarm#8]
When I tried to build the project, I get [this error](https://forums.unrealengine.com/showthread.php?748-Error-Lightmap-UV-are-overlapping-by-40). @PixelKitteh  I think it has something to do with the models? Because after rendering, the field and ball doesn't look like it's getting proper lighting.

Here is the error:

![lightmap overlap](https://cloud.githubusercontent.com/assets/1505448/17448995/a8449724-5b14-11e6-876e-dd2d04bd6bed.PNG)

**Comment by PixelKitteh** [comment]
Might be the way I imported the object as a full item, instead of individual objects.  I will separate the field and the fence.

**Comment by iwatakeshi** [comment]
Were you using blender to create the models? Maybe [this YouTube channel](https://www.youtube.com/channel/UCaCPXjYfbTVvWNAJ6_EGrZA) might help?
