### ISSUE TITLE
Moving to Unity

### ISSUE THREAD

**Issue by iwatakeshi** [pokefarm/soccerfarm#9]
So, since there isn't much progress and the deadline is almost here, I decided to try out Unity using the assets that were used in Unreal (converting it to FBX). Surprisingly, I already have a working game compared to Unreal where we still have #8 as an issue. 

To check out the unity game I created (in 5 hours), click on the small down arrow at the top left (where it says "master") : 
![github](https://cloud.githubusercontent.com/assets/1505448/17580567/cf8d7b4c-5f5c-11e6-8d93-a13afa654e22.PNG)

Then it should say "unity" instead of "master". This means we have "checked-out"/downloaded the "unity" branch.

![github](https://cloud.githubusercontent.com/assets/1505448/17580596/0725a318-5f5d-11e6-8427-7d8e2e2c81ca.PNG)

The game is by no means perfect but it's pretty good for a game done in 5 hours or so.

**Comment by PixelKitteh** [comment]
I can download Unity after my vacation and I will take a look at it.  Are my fbx files working on Unity then?

**Comment by iwatakeshi** [comment]
Yup, I didn't have any issues and according to the documentation, FBX files are supported. I did have to export the assets from Unreal (batch export) and import them to Unity since I didn't have the original files but I didn't see any issues from the start.

**Comment by PixelKitteh** [comment]
In that case, I think I'm ok with transferring to Unity as long as you are comfortable programming purely in C.  I won't be able to help in that myself, but I can learn the design aspect just as I did for Unreal, so that shouldn't be a problem.

**Comment by iwatakeshi** [comment]
I'm fairly [comfortable with C#](https://github.com/iwatakeshi/Metal), so that's not a problem and it's just a matter of googling. I'm all for Unity, as I find it a bit easier to navigate, and writing actual code for me is easier as well unlike Unreal where blueprints is new to me (sorry @Dstar99 ).
